/** Krátké označení ligy podle klubu (soupisky 2025–26 v datech projektu). */
const CLUB_TO_LEAGUE: Record<string, string> = {
  "Abbotsford Canucks": "AHL",
  "Adler Mannheim": "DEL",
  "Anaheim Ducks": "NHL",
  "BK Mladá Boleslav": "Tipsport Extraliga",
  "Belleville Senators": "AHL",
  "Boston Bruins": "NHL",
  "Bridgeport Islanders": "AHL",
  "Brynäs IF": "SHL",
  "Buffalo Sabres": "NHL",
  "Bílí Tygři Liberec": "Tipsport Extraliga",
  "Calgary Flames": "NHL",
  "Calgary Wranglers": "AHL",
  "Charlotte Checkers": "AHL",
  "Chicago Wolves": "AHL",
  "Cleveland Monsters": "AHL",
  "Coachella Valley Firebirds": "AHL",
  "Colorado Avalanche": "NHL",
  "Colorado Eagles": "AHL",
  "Dallas Stars": "NHL",
  "EHC Biel-Bienne": "NL",
  "EHC Kloten": "NL",
  "EV Zug": "NL",
  "Edmonton Oilers": "NHL",
  "Florida Panthers": "NHL",
  "Färjestad BK": "SHL",
  "Genève-Servette HC": "NL",
  "Grand Rapids Griffins": "AHL",
  "Ambri-Piotta": "NL",
  "HC Ambrì-Piotta": "NL",
  "HC Davos": "NL",
  "EHC Red Bull Munchen": "DEL",
  "EHC Red Bull München": "DEL",
  "HC Dynamo Pardubice": "Tipsport Extraliga",
  "HC Energie Karlovy Vary": "Tipsport Extraliga",
  "HC Fribourg-Gottéron": "NL",
  "HC Kometa Brno": "Tipsport Extraliga",
  "HC Litvínov": "Tipsport Extraliga",
  "HC Lugano": "NL",
  "HC Motor České Budějovice": "Tipsport Extraliga",
  "HC Oceláři Třinec": "Tipsport Extraliga",
  "HC Olomouc": "Tipsport Extraliga",
  "HC Plzeň": "Tipsport Extraliga",
  "HC Sparta Praha": "Tipsport Extraliga",
  "HC Verva Litvínov": "Tipsport Extraliga",
  "HC Vítkovice": "Tipsport Extraliga",
  "HV71": "SHL",
  "Henderson Silver Knights": "AHL",
  "Iowa Wild": "AHL",
  "IFK Helsinky": "Liiga",
  "Ilves": "Liiga",
  "KalPa": "Liiga",
  "KooKoo": "Liiga",
  "Kärpät": "Liiga",
  "Linköping HC": "SHL",
  "Lukko": "Liiga",
  "Malmö Redhawks": "SHL",
  "Minnesota Wild": "NHL",
  "Montréal Canadiens": "NHL",
  "Mountfield HK": "Tipsport Extraliga",
  "New Jersey Devils": "NHL",
  "New York Islanders": "NHL",
  "New York Rangers": "NHL",
  "Straubing Tigers": "DEL",
  "Ontario Reign": "AHL",
  "Pelicans": "Liiga",
  "Philadelphia Flyers": "NHL",
  "Providence Bruins": "AHL",
  "Rochester Americans": "AHL",
  "Rytíři Kladno": "Tipsport Extraliga",
  "Rögle BK": "SHL",
  "SCL Tigers": "NL",
  "SaiPa": "Liiga",
  "San Diego Gulls": "AHL",
  "San Jose Barracuda": "AHL",
  "San Jose Sharks": "NHL",
  "Sport": "Liiga",
  "Springfield Thunderbirds": "AHL",
  "Syracuse Crunch": "AHL",
  "Tappara": "Liiga",
  "Toronto Maple Leafs": "NHL",
  "Tucson Roadrunners": "AHL",
  "Utah Mammoth": "NHL",
  "Utica Comets": "AHL",
  "Vancouver Canucks": "NHL",
  "Vegas Golden Knights": "NHL",
  "Washington Capitals": "NHL",
  "ZSC Lions": "NL",
  "Ässät": "Liiga",
};

export function leagueForClub(club: string): string {
  const key = club.trim();
  return CLUB_TO_LEAGUE[key] ?? "–";
}
