// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs";
import { join } from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const root = process.cwd();
const localPath = join(root, ".env.local");
const envPath = join(root, ".env");

if (existsSync(localPath)) config({ path: localPath, override: true });
if (existsSync(envPath)) config({ path: envPath });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed:
      "npx ts-node -r tsconfig-paths/register --project scripts/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
